# try - catch

try :
    print(10/0)

except:
    print('0으로 못나눈다')